# Generated by Django 5.2 on 2025-12-31 00:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Floorplan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[("2d", "2D"), ("3d", "3D")],
                        max_length=2,
                        verbose_name="Grundriss-Typ",
                    ),
                ),
                (
                    "number_of_floorplans",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Anzahl Grundrisse",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=255, verbose_name="Vorname"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=255, verbose_name="Nachname"),
                ),
                ("street", models.CharField(max_length=255, verbose_name="Straße")),
                (
                    "postcode",
                    models.CharField(max_length=5, verbose_name="Postleitzahl"),
                ),
                ("city", models.CharField(max_length=255, verbose_name="Stadt")),
                ("country", models.CharField(max_length=255, verbose_name="Land")),
                (
                    "furniture_style",
                    models.CharField(
                        choices=[("modern", "Modern"), ("archaic", "Traditionell")],
                        default="modern",
                        max_length=255,
                        verbose_name="Einrichtungsstil",
                    ),
                ),
                (
                    "show_measurements",
                    models.BooleanField(
                        default=False, verbose_name="Maße im Grundriss anzeigen"
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        choices=[("1080", "1080p"), ("2160", "2160p")],
                        default="1080",
                        max_length=255,
                        verbose_name="Auflösung",
                    ),
                ),
                (
                    "show_furniture",
                    models.BooleanField(default=False, verbose_name="Möbel anzeigen"),
                ),
            ],
        ),
    ]
