# Generated by Django 5.2 on 2025-12-30 23:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floorplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('2d', '2D'), ('3d', '3D')], max_length=2, verbose_name='Grundriss-Typ')),
                ('number_of_floorplans', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Anzahl Grundrisse')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('furniture_style', models.CharField(choices=[('modern', 'Modern'), ('archaic', 'Traditionell')], default='modern', max_length=255, verbose_name='Einrichtungsstil')),
                ('show_measurements', models.BooleanField(default=False, verbose_name='Maße im Grundriss anzeigen')),
                ('resolution', models.CharField(choices=[('1080', '1080p'), ('2160', '2160p')], default='1080', max_length=255, verbose_name='Auflösung')),
                ('show_furniture', models.BooleanField(default=False, verbose_name='Möbel anzeigen')),
            ],
        ),
    ]
